export class CreaFormaPagoEntity {
    constructor(
        public Numero?: number,
        public Linea?: number,
        public ValorRecibido?: number,
        public Moneda?: string,
        public DocumentoCaja?: string,
        public TarjetaCaja?: string,
        public NumeroCuentaCaja?: string,
        public FechaCreacion?: Date,
        public HoraCreacion?: string,
        public UsuarioCreacion?: string,
        public ProgramaCreacion?: string,
        public FechaModificacion?: Date,
        public HoraModificacion?: string,
        public UsuarioModificacion?: string,
        public ProgramaModificacion?: string,
        public BancoCaja?: number,
        public TipoPago?: string,
        public FechaCaja?: Date,
        public LugarPago?: string,
        public Estado?: number,
        public EsPrimeraCuota?: boolean,
        public NumeroAutorizacion?: string,
        public FechaEmision?: Date,
        public FechaFin?: Date,
        public Direccion?: string,
        public Telefono?: string,
        public FechaIncurrencia?: Date,
        public RucPrestador?: string,
        public TipoEmision?: string,
        public TarjetaCodigoBanco?: number,
        public FormaTipoPago?: string
    ) { }
}