export class CreaPagoEntity {
    constructor(
        public Numero?: number,
        public EmpresaNumero?: number,
        public SucursalEmpresa?: number,
        public SucursalNombre?: string,
        public ValorRetencion?: number,
        public TipoPago?: string,
        public RucEmpresa?: string,
        public TipoDocumento?: string,
        public PorcentajeIva?: number,
        public ValorAplicaIva?: number,
        public ValorNoAplicaIva?: number,
        public BancoCaja?: number,
        public FechaAnulacion?: Date,
        public FechaCaja?: Date,
        public Moneda?: string,
        public CuotasAplicadas?: number,
        public ValorAplicado?: number,
        public ValorDescuento?: number,
        public ValorInteres?: number,
        public ValorIva?: number,
        public ValorRecibido?: number,
        public DocumentoCaja?: string,
        public TarjetaCaja?: string,
        public NumeroCuentaCaja?: string,
        public ContratoNumero?: number,
        public ValorAFavorAplicado?: number,
        public ValorSobrante?: number,
        public LugarPago?: string,
        public EstadoPago?: number,
        public CodigoProducto?: string,
        public MotivoNota?: string,
        public Region?: string,
        public FechaCreacion?: Date,
        public HoraCreacion?: string,
        public UsuarioCreacion?: string,
        public ProgramaCreacion?: string,
        public FechaModificacion?: Date,
        public HoraModificacion?: string,
        public UsuarioModificacion?: string,
        public ProgramaModificacion?: string,
        public EsPrimeraCuota?: boolean,
        public Migrado?: boolean,
        public FechaMigracion?: Date,
        public NumeroAutorizacion?: string,
        public FechaEmision?: Date,
        public FechaCaducidad?: Date,
        public NumeroRetencion?: string,
        public FormaTipoPago?: string,
        public TablaFormaPago?: ListaTablaPagoRecaudo[],
        public AuxNumeroSerie?: number,
        public NombreCaja?: string
    ) { }
}

export class ListaTablaPagoRecaudo {
    constructor(
        public NumeroPago?: number,
        public CodFormaPago?: string,
        public NombreFormaPago?: string,
        public CodBanco?: number,
        public NombreBanco?: string,
        public CodBancoTarjeta?: string,
        public NombreBancoTarjeta?: string,
        public NroCuenta?: string,
        public NroDocumento?: string,
        public ValorRecibido?: number

    ) { }
}