export class Sucursal {
    constructor(public   NumeroEmpresa ?: number,
                public   Empresa ?: string,
                public   Numero ?: number,
                public   CodigoAgenteVenta ?: number,
                public   AgenteVenta ?: string,
                public   Nombre ?: string,
                public   CodigoCiudad ?: number,
                public   Ciudad ?: string,
                public   Barrio ?: string,
                public   Calle ?: string,
                public   Zona ?: string,
                public   Casilla ?: string,
                public   Telefono ?: string,
                public   Fax ?: string,
                public   Email ?: string,
                public   NombresRepresentante ?: string,
                public   ApellidosRepresentante ?: string,
                public   CargoRepresentante ?: string,
                public   CedulaRepresentante ?: string,
                public   CodigoSucursal ?: number,
                public   Sucursal ?: string,
                public   PresentaGarantia ?: boolean,
                public   FormaPago ?: number,
                public   TipoCuenta ?: string,
                public   Moneda ?: string,
                public   CodigoBanco ?: number,
                public   Banco ?: string,
                public   PeriodoPago ?: number,
                public   NumeroCuenta ?: string,
                public   NumeroContratoDebito ?: string,
                public   NombreDuenioCuenta ?: string,
                public   FacturarACedula ?: string,
                public   FacturarARuc ?: string,
                public   NumeroContratos ?: number,
                public   FechaInicio ?: Date,
                public   FechaFin ?: Date,
                public   CodigoUnidadResponsable ?: string,
                public   UnidadResponsable ?: string,
                public   FechaFinTarjeta ?: Date,
                public   CodigoProducto ?: string,
                public   ValorTarjetas ?: number,
                public   TarjetasAdicionales ?: number,
                public   ValorTarjetasAdicionales ?: number,
                public   Region ?: string,
                public   FechaUltimoPeriodo ?: Date,
                public   MesesFormaPago ?: number,
                public   EsBloqueada ?: boolean,
                public   FechaBloqueo ?: Date,
                public   CodigoEstado ?: number,
                public   Estado ?: string,
                public   ProductoAfectaCosto ?: string,
                public   PagaComision ?: boolean,
                public   EsSuscripcion ?: boolean,
                public   PorcentajeComisionBroker ?: number,
                public   AtiendeReembolsosLocales ?: boolean,
                public   NumeroOdas ?: number,
                public   CodigoEjecutivo ?: number,
                public   Ejecutivo ?: string,
                public   TelefonoLista ?: string,
                public   FaxLista ?: string,
                public   DigitadorCreacion ?: string,
                public   FechaCreacion ?: Date,
                public   HoraCreacion ?: string,
                public   FechaModificacion ?: Date,
                public   DigitadorModificacion ?: string,
                public   HoraModificacion ?: string,
                public   FechaAnulacion ?: Date,
                public   DigitadorAnulacion ?: string,
                public   HoraAnulacion ?: string,
                public   CodigoUnidadAgente ?: number,
                public   CodigoAgente ?: string,
                public   MontoMora ?: number,
                public   FechaFinOriginal ?: Date,
                public   FechaInicioOriginal ?: Date,
                public   EsFacturadoSaludsa ?: boolean,
                public   CodigoMotivoBloqueo ?: number,
                public   MotivoBloqueo ?: string,
                public   CodigoAgenteContacto ?: number,
                public   AgenteContacto ?: string,
                public   EsPagoInteligente ?: boolean,
                public   EmailRrhh ?: string,
                public   EmailBroker ?: string,
                public   BloqueoOdas ?: boolean,
                public   BloqueoReclamos ?: boolean,
                public   BloqueoCheques ?: boolean,
                public   BloqueoCreditos ?: boolean,
                public   AdmiteOdas ?: boolean,
                public   TipoTarjeta ?: string,
                public   EsMedicoDomicilio ?: boolean,
                public   NombreTarjeta ?: string,
                public   AtencionBiored ?: string,
                public   ReferenciaEnvio ?: string,
                public   EsServiciosAdicionales ?: boolean,
                public   TieneTarjeta ?: boolean,
                public   ContactoDocumentosElectronicos ?: string,
                public   EmailContactoDocumentosElectronicos ?: string,
                public   EmailBrokerDocumentosElectronicos ?: string,
                public   EmailDocumentosElectronicos ?: string,
                public   CedulaPagoReclamos ?: string,
                public   NombrePagoReclamos ?: string,
                public   TipoLista ?: string,
                public   RucPagoReclamos ?: string,
                public   CodigoBancoPagoReclamo ?: number,
                public   BancoPagoReclamo ?: string,
                public   TipoCuentaReclamo ?: string,
                public   CuentaPagoReclamo ?: string,
                public   Linea1 ?: string,
                public   Linea2 ?: string,
                public   Linea3 ?: string,
                public   TieneRetencion ?: boolean,
                public   TipoGrupal ?: string,
                public   PorcentajeDescuento ?: number,
                public   CodigoMotivoAnulacion ?: number,
                public   MotivoAnulacion ?: string,
                public   EmailSucursalDocumentosElectronicos ?: string,
                public   EsTransicion ?: boolean,
                public   FechaInicioVigencia ?: Date,
                public   FechaFinVigencia ?: Date,
                public   EsAplicadoTransicion ?: boolean,
                public   TipoCobertura ?: string,
                public   EsOpcional ?: boolean,
                public   EsCheckeado ?: boolean,
                public  Alias ?: string,
                public   EsObligatorio ?: boolean,
                public   EsHabilitado?: boolean,
                public   SeleccionConfiguracion?:number,
                public  Configuracion ?: string) {
    }
}

export class SucursarList {
    constructor(public   NumeroEmpresa ?: number,
                public   Empresa ?: string,
                public   Numero ?: number,
                public   CodigoAgenteVenta ?: number,
                public   AgenteVenta ?: string,
                public   Nombre ?: string,
                public   CodigoCiudad ?: number,
                public   Ciudad ?: string,
                public   Barrio ?: string,
                public   Calle ?: string,
                public   Zona ?: string,
                public   Casilla ?: string,
                public   Telefono ?: string,
                public   Fax ?: string,
                public   Email ?: string,
                public   NombresRepresentante ?: string,
                public   ApellidosRepresentante ?: string,
                public   CargoRepresentante ?: string,
                public   CedulaRepresentante ?: string,
                public   CodigoSucursal ?: number,
                public   Sucursal ?: string,
                public   PresentaGarantia ?: boolean,
                public   FormaPago ?: number,
                public   TipoCuenta ?: string,
                public   Moneda ?: string,
                public   CodigoBanco ?: number,
                public   Banco ?: string,
                public   PeriodoPago ?: number,
                public   NumeroCuenta ?: string,
                public   NumeroContratoDebito ?: string,
                public   NombreDuenioCuenta ?: string,
                public   FacturarACedula ?: string,
                public   FacturarARuc ?: string,
                public   NumeroContratos ?: number,
                public   FechaInicio ?: Date,
                public   FechaFin ?: Date,
                public   CodigoUnidadResponsable ?: string,
                public   UnidadResponsable ?: string,
                public   FechaFinTarjeta ?: Date,
                public   CodigoProducto ?: string,
                public   ValorTarjetas ?: number,
                public   TarjetasAdicionales ?: number,
                public   ValorTarjetasAdicionales ?: number,
                public   Region ?: string,
                public   FechaUltimoPeriodo ?: Date,
                public   MesesFormaPago ?: number,
                public   EsBloqueada ?: boolean,
                public   FechaBloqueo ?: Date,
                public   CodigoEstado ?: number,
                public   Estado ?: string,
                public   ProductoAfectaCosto ?: string,
                public   PagaComision ?: boolean,
                public   EsSuscripcion ?: boolean,
                public   PorcentajeComisionBroker ?: number,
                public   AtiendeReembolsosLocales ?: boolean,
                public   NumeroOdas ?: number,
                public   CodigoEjecutivo ?: number,
                public   Ejecutivo ?: string,
                public   TelefonoLista ?: string,
                public   FaxLista ?: string,
                public   DigitadorCreacion ?: string,
                public   FechaCreacion ?: Date,
                public   HoraCreacion ?: string,
                public   FechaModificacion ?: Date,
                public   DigitadorModificacion ?: string,
                public   HoraModificacion ?: string,
                public   FechaAnulacion ?: Date,
                public   DigitadorAnulacion ?: string,
                public   HoraAnulacion ?: string,
                public   CodigoUnidadAgente ?: number,
                public   CodigoAgente ?: string,
                public   MontoMora ?: number,
                public   FechaFinOriginal ?: Date,
                public   FechaInicioOriginal ?: Date,
                public   EsFacturadoSaludsa ?: boolean,
                public   CodigoMotivoBloqueo ?: number,
                public   MotivoBloqueo ?: string,
                public   CodigoAgenteContacto ?: number,
                public   AgenteContacto ?: string,
                public   EsPagoInteligente ?: boolean,
                public   EmailRrhh ?: string,
                public   EmailBroker ?: string,
                public   BloqueoOdas ?: boolean,
                public   BloqueoReclamos ?: boolean,
                public   BloqueoCheques ?: boolean,
                public   BloqueoCreditos ?: boolean,
                public   AdmiteOdas ?: boolean,
                public   TipoTarjeta ?: string,
                public   EsMedicoDomicilio ?: boolean,
                public   NombreTarjeta ?: string,
                public   AtencionBiored ?: string,
                public   ReferenciaEnvio ?: string,
                public   EsServiciosAdicionales ?: boolean,
                public   TieneTarjeta ?: boolean,
                public   ContactoDocumentosElectronicos ?: string,
                public   EmailContactoDocumentosElectronicos ?: string,
                public   EmailBrokerDocumentosElectronicos ?: string,
                public   EmailDocumentosElectronicos ?: string,
                public   CedulaPagoReclamos ?: string,
                public   NombrePagoReclamos ?: string,
                public   TipoLista ?: string,
                public   RucPagoReclamos ?: string,
                public   CodigoBancoPagoReclamo ?: number,
                public   BancoPagoReclamo ?: string,
                public   TipoCuentaReclamo ?: string,
                public   CuentaPagoReclamo ?: string,
                public   Linea1 ?: string,
                public   Linea2 ?: string,
                public   Linea3 ?: string,
                public   TieneRetencion ?: boolean,
                public   TipoGrupal ?: string,
                public   PorcentajeDescuento ?: number,
                public   CodigoMotivoAnulacion ?: number,
                public   MotivoAnulacion ?: string,
                public   EmailSucursalDocumentosElectronicos ?: string,
                public   EsTransicion ?: boolean,
                public   FechaInicioVigencia ?: Date,
                public   FechaFinVigencia ?: Date,
                public   EsAplicadoTransicion ?: boolean,
                public   TipoCobertura ?: string,
                public   Alias ?: string,
                public   EsOpcional ?: boolean,
                public  Configuracion ?: string) {
    }
}

export class SucursalNombre {
    constructor
    (public nivel?: string,
     public max?: string,
     public descripcion?: string,
     public producto?: string,
     public coberturas?: string,
     public esOpcional?: boolean,
     public sucursal?: Sucursal,
     public alias?: string,
     public subSucursal?:string
    ) {
    }
}

export class SucursalFilter {
    constructor(public NumeroEmpresa?: number,
                public Empresa?: string,
                public Numero?: number) {
    }
}

export class SubSucursal {
    constructor(public id?: number,
                public cobertura?: string,
                public plan?: string,
                public opcional?: boolean,
                public alias?:string) {
    }
}

