import { Injectable } from '@angular/core';

@Injectable()
export class ConstantesComercialService {

  //EJECUTIVO COMERCIAL

  /**PARA EL SERVICIO DE VENTAS REALIZADO POR JUANPA*/
  FILTRO_ESTADO_ACTIVO_AGENTE: string;
  FILTRO_ESTADO_INACTIVO_AGENTE: string;
  FILTRO_TODOS_ESTADOS_AGENTE: string;
  FILTRO_TODOS_CODIGO_AGENTE: number;
  FILTRO_TODAS_REGIONES: string;
  FILTRO_TODOS_NOMBRE_AGENTE: string;
  CODIGO_GRUPO_BROKER: number;
  CODIGO_TIPO_BROKER: number;

  TIPO_SERIE_EMISOR: string;
  TIPO_SERIE_RECEPTOR: string;
  TIPO_FUN_RECEPTOR: string;

  GRUPO_VENDEDORES: string;

  //UIO
  TIPO_TRANSACCION_ACTUALIZAR: string;
  TIPO_TRANSACCION_INGRESAR: string;

  TIPO_AGENTE_VENTA_VENDEDOR: string;

  TIPO_AGENTE_VENTA_DIRECTOR: string;
  INACTIVO: number; 
  ACTIVO: number; 
  INDEFINIDO: number;

  constructor() {
    this.FILTRO_ESTADO_ACTIVO_AGENTE = "A";
    this.FILTRO_ESTADO_INACTIVO_AGENTE = "I";
    this.FILTRO_TODOS_ESTADOS_AGENTE = "TODOS";
    this.FILTRO_TODOS_CODIGO_AGENTE = 0
    this.FILTRO_TODAS_REGIONES = "TODOS";
    this.FILTRO_TODOS_NOMBRE_AGENTE = "TODOS";
    this.CODIGO_GRUPO_BROKER = 1;
    this.CODIGO_TIPO_BROKER = 19;
    this.TIPO_TRANSACCION_ACTUALIZAR = "ACTUALIZAR";
    this.TIPO_TRANSACCION_INGRESAR = "INGRESAR";

    this.TIPO_SERIE_EMISOR = "SERIE_EMISOR";
    this.TIPO_SERIE_RECEPTOR = "SERIE_RECEPTOR";
    this.TIPO_FUN_RECEPTOR = "FUN_RECEPTOR";

    this.TIPO_AGENTE_VENTA_VENDEDOR = "Vendedor";
    this.TIPO_AGENTE_VENTA_DIRECTOR = "Director";
    this.GRUPO_VENDEDORES = "PANDA\\GR Jefes";

    this.ACTIVO = 1; 
    this.INACTIVO = 2; 
    this.INDEFINIDO = 0;
  }
}